const poemData = [
    { text: "楚", py: "chǔ", zh: "楚国。", en: "The State of Chu." },
    { text: "有", py: "yǒu", zh: "有一个。", en: "There was a person who" },
    { text: "祠者", py: "cí zhě", zh: "举行祭祀的人。“祠”，春祭，这里泛指祭祀。", en: "offered sacrifices.", exam: true },
    { text: "，", punc: true },
    { text: "赐", py: "cì", zh: "赏赐，给予。", en: "He rewarded" },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "舍人", py: "shè rén", zh: "门客，左右随从属官。", en: "retainers with", exam: true },
    { text: "卮", py: "zhī", zh: "古代的一种盛酒器，类似于杯。", en: "a goblet of", exam: true },
    { text: "酒", py: "jiǔ", zh: "酒。", en: "wine." },
    { text: "。", punc: true },
    { text: "舍人", py: "shè rén", zh: "门客们。", en: "The retainers" },
    { text: "相谓", py: "xiāng wèi", zh: "互相商量，互相说。“相”，互相。", en: "said to one another:", exam: true },
    { text: "曰", py: "yuē", zh: "说。", en: "saying" },
    { text: "：“", punc: true },
    { text: "数人", py: "shù rén", zh: "几个人。", en: "If several people" },
    { text: "饮", py: "yǐn", zh: "喝。", en: "drink" },
    { text: "之", py: "zhī", zh: "代词，它（指这杯酒）。", en: "it," },
    { text: "不足", py: "bù zú", zh: "不够。", en: "it is not enough;" },
    { text: "，", punc: true },
    { text: "一人", py: "yī rén", zh: "一个人。", en: "if one person" },
    { text: "饮", py: "yǐn", zh: "喝。", en: "drinks" },
    { text: "之", py: "zhī", zh: "它。", en: "it," },
    { text: "有余", py: "yǒu yú", zh: "有剩余，足够了。", en: "there is more than enough." },
    { text: "。", punc: true },
    { text: "请", py: "qǐng", zh: "请允许我们，让我们……（表提议）。", en: "Let us" },
    { text: "画地", py: "huà dì", zh: "在地上画画。", en: "draw on the ground" },
    { text: "为", py: "wéi", zh: "画作，作为。", en: "to make a" },
    { text: "蛇", py: "shé", zh: "蛇。", en: "snake," },
    { text: "，", punc: true },
    { text: "先", py: "xiān", zh: "最先，首先。", en: "and whoever finishes" },
    { text: "成者", py: "chéng zhě", zh: "画好的人。", en: "first" },
    { text: "饮", py: "yǐn", zh: "喝。", en: "shall drink" },
    { text: "酒", py: "jiǔ", zh: "酒。", en: "the wine.”" },
    { text: "。”", punc: true },
    { text: "一人", py: "yī rén", zh: "其中一个人。", en: "One person" },
    { text: "蛇", py: "shé", zh: "蛇。", en: "his snake" },
    { text: "先", py: "xiān", zh: "最先。", en: "first," },
    { text: "成", py: "chéng", zh: "完成，画好。", en: "finished" },
    { text: "，", punc: true },
    { text: "引", py: "yǐn", zh: "伸手拿过，端起（盛酒器）。", en: "drew toward him", exam: true },
    { text: "酒", py: "jiǔ", zh: "酒。", en: "the wine" },
    { text: "且", py: "qiě", zh: "副词，准备，将要。", en: "and was about to", exam: true },
    { text: "饮", py: "yǐn", zh: "喝。", en: "drink" },
    { text: "之", py: "zhī", zh: "它。", en: "it," },
    { text: "，", punc: true },
    { text: "乃", py: "nǎi", zh: "连词，于是，就。", en: "then" },
    { text: "左手", py: "zuǒ shǒu", zh: "左手。", en: "holding the cup with his left hand," },
    { text: "持", py: "chí", zh: "拿着，执持。", en: "held" },
    { text: "卮", py: "zhī", zh: "酒杯。", en: "the goblet" },
    { text: "，", punc: true },
    { text: "右手", py: "yòu shǒu", zh: "右手。", en: "while drawing the snake with his right hand," },
    { text: "画", py: "huà", zh: "画。", en: "and drawing" },
    { text: "蛇", py: "shé", zh: "蛇。", en: "the snake" },
    { text: "曰", py: "yuē", zh: "说。", en: "said:" },
    { text: "：“", punc: true },
    { text: "吾", py: "wú", zh: "我。", en: "“I" },
    { text: "能", py: "néng", zh: "能够。", en: "can even" },
    { text: "为", py: "wéi", zh: "替，给。", en: "make" },
    { text: "之", py: "zhī", zh: "代词，它（指蛇）。", en: "it" },
    { text: "足", py: "zú", zh: "脚，爪子。", en: "feet!”" },
    { text: "！”", punc: true },
    { text: "未", py: "wèi", zh: "还没有（完成）。", en: "Before he" },
    { text: "成", py: "chéng", zh: "画好（蛇脚）。", en: "finished," },
    { text: "，", punc: true },
    { text: "一人", py: "yī rén", zh: "另一个人。", en: "another person" },
    { text: "之", py: "zhī", zh: "的。", en: "的" },
    { text: "蛇", py: "shé", zh: "蛇。", en: "snake" },
    { text: "成", py: "chéng", zh: "完成了。", en: "was done," },
    { text: "，", punc: true },
    { text: "夺", py: "duó", zh: "夺过，抢走。", en: "snatched" },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "卮", py: "zhī", zh: "酒杯。", en: "goblet" },
    { text: "曰", py: "yuē", zh: "说。", en: "and said:" },
    { text: "：“", punc: true },
    { text: "蛇", py: "shé", zh: "蛇。", en: "“Snakes" },
    { text: "固", py: "gù", zh: "副词，本来，原来。", en: "inherently", exam: true },
    { text: "无", py: "wú", zh: "没有。", en: "have no" },
    { text: "足", py: "zú", zh: "脚。", en: "feet," },
    { text: "，", punc: true },
    { text: "子", py: "zǐ", zh: "代词，你（古代对男子的尊称）。", en: "how", exam: true },
    { text: "安", py: "ān", zh: "疑问代词，怎么，哪里。", en: "can", exam: true },
    { text: "能", py: "néng", zh: "能够。", en: "you" },
    { text: "为", py: "wéi", zh: "给，画。", en: "make" },
    { text: "之", py: "zhī", zh: "它。", en: "it" },
    { text: "足", py: "zú", zh: "脚？法”", en: "feet?”" },
    { text: "？”", punc: true },
    { text: "遂", py: "suì", zh: "于是，就。", en: "So he then" },
    { text: "饮", py: "yǐn", zh: "喝了。", en: "drank" },
    { text: "其", py: "qí", zh: "那杯。", en: "the" },
    { text: "酒", py: "jiǔ", zh: "酒。", en: "wine." },
    { text: "。", punc: true },
    { text: "为", py: "wéi", zh: "给，作。", en: "He who made" },
    { text: "蛇", py: "shé", zh: "蛇。", en: "the snake's" },
    { text: "足", py: "zú", zh: "脚。", en: "feet," },
    { text: "者", py: "zhě", zh: "的人。", en: "person," },
    { text: "，", punc: true },
    { text: "终", py: "zhōng", zh: "最终，结果。", en: "ultimately", exam: true },
    { text: "亡", py: "wáng", zh: "动词，丢失，失去（古汉语中同“无”，此处作失去解）。", en: "lost", exam: true },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "酒", py: "jiǔ", zh: "酒。", en: "wine." },
    { text: "。", punc: true }
];
